### **Part 1: Theoretical Questions**

1. **What are the different data structures used in Tensorflow ?. Give some examples.**

2. **How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.**

3. **Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.**

**Ans :-**

#### 1. **Different Data Structures Used in TensorFlow**

  -  TensorFlow uses a variety of data structures for handling data, including :

      - **Tensors -** The fundamental data structure in TensorFlow. It is a multi-dimensional array of elements. Tensors have a rank (number of dimensions), shape (size of each dimension), and data type (such as `float32`, `int32`, etc.). Tensors are used for almost every operation in TensorFlow.
        
        - **Example :** `tf.Tensor([1, 2, 3], dtype=tf.float32)` 

      - **Variables -** A mutable tensor that can be updated during model training. Variables store the state of a model, such as weights and biases in neural networks.
        
        - **Example :** `tf.Variable([1, 2, 3], dtype=tf.float32)`

      - **Constants -** Immutable tensors whose values are set at the start and cannot be changed.
        
        - **Example :** `tf.constant([1, 2, 3], dtype=tf.float32)`

      - **Placeholders (Deprecated) -** Previously, placeholders were used to feed external data during model execution, but now replaced by `tf.function` and eager execution.
        
        - **Example (Old) :** `tf.placeholder(tf.float32)`

      - **Sparse Tensors -** A tensor that is primarily filled with zeros, useful for memory efficiency.
        
        - **Example :** `tf.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])`

      - **Ragged Tensors -** Tensors with variable-length dimensions.
        
        - **Example :** `tf.RaggedTensor.from_row_splits(values=[1, 2, 3, 4, 5], row_splits=[0, 3, 5])`

      - **TensorArray -** Used for dynamic computation graphs, for storing lists of tensors that might change during graph execution.
       
        - **Example :** `tf.TensorArray(dtype=tf.float32, size=3)`

#### 2. **Difference Between TensorFlow Constant and TensorFlow Variable**

  - **TensorFlow Constant -**
    
    - **Immutable :** The value of a constant is fixed at the time of creation and cannot be changed.
    
    - **Usage**: Best suited for storing values that remain the same throughout the execution, such as configuration values or fixed hyperparameters.

  - **TensorFlow Variable -**
    
    - **Mutable :** Variables allow their values to be updated during the model's training process, such as weights or biases.
    
    - **Usage :** Used to store parameters that need to be updated, such as model weights during backpropagation in neural networks.

**Key Difference -** Constants are immutable and cannot be changed once assigned, while variables can be updated and changed throughout the execution of the model.

**Example -**

In [14]:
import tensorflow as tf
const = tf.constant(5.0)
print(f"TensorFlow Constant :-")
print(const)

var = tf.Variable(5.0)
print(f"\nTensorFlow Variable :-")
print(var)
  
  # Updating the variable
var.assign(10.0)
print(var)

TensorFlow Constant :-
tf.Tensor(5.0, shape=(), dtype=float32)

TensorFlow Variable :-
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.0>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=10.0>


#### 3. **Matrix Operations in TensorFlow**

- **Matrix Addition -** Matrix addition in TensorFlow is done element-wise between two tensors of the same shape.

- **Matrix Multiplication -** Matrix multiplication is performed using the `tf.matmul()` function in TensorFlow, following the rules of matrix multiplication (dot product).

- **Element-wise Operations -** Element-wise operations are performed by applying operations directly between tensors of the same shape. TensorFlow functions like `tf.multiply()` and `tf.add()` can be used.

**Example -**

In [16]:
import tensorflow as tf

A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])

C = tf.add(A, B)  # Element-wise addition
print(f"Matrix Addition :-")
print(C)

C = tf.matmul(A, B)  # Matrix multiplication
print(f"\nMatrix Multiplication :-")
print(C)

C = tf.multiply(A, B)  # Element-wise multiplication
print(f"\nElement-wise Operations :-")
print(C)

Matrix Addition :-
tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)

Matrix Multiplication :-
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)

Element-wise Operations :-
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

### **Part 2: Practical Implementation**
#### **Task 1: Creating and Manipulating Matrices**

1. **Create a normal matrix A with dimensions 3x3, using TensorFlow's random_normal function. Display the values of matrix A.**

2. **Create a Gaussian matrix B with dimensions 4x4, using TensorFlow's truncated_normal function. Display the values of matrix B.**

3. **Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 3 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C.**

4. **Perform matrix addition between matrix A and matrix B, and store the result in matrix D.**

5. **Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.**

#### **Task 2: Performing Additional Matrix Operations**

1. **Create a matrix F with dimensions 3x3, initialized with random values using TensorFlow's random_uniform function.**

2. **Calculate the transpose of matrix F and store the result in matrix G.**

3. **Calculate the element-wise exponential of matrix F and store the result in matrix H.**

4. **Create a matrix I by concatenating matrix F and matrix G horizontally.**

5. **Create a matrix J by concatenating matrix F and matrix H vertically.**

**Ans :-**

#### **Import Necessary Libraries**

In [36]:
import tensorflow as tf

#### **Task 1: Creating and Manipulating Matrices**

1. **Create a normal matrix A with dimensions 3x3 using TensorFlow's random_normal function**

In [46]:
A = tf.random.normal(shape=(3, 3))
print("Matrix A -")
print(A.numpy())

Matrix A -
[[ 0.52103037  0.0370561   1.166493  ]
 [-0.06264463  2.0344625   1.3230577 ]
 [ 1.2421511  -0.6378275  -0.5019292 ]]


2. **Create a Gaussian matrix B with dimensions 4x4 using TensorFlow's truncated_normal function**

In [48]:
B = tf.random.truncated_normal(shape=(3, 3))
print("Matrix B -")
print(B.numpy())

Matrix B -
[[ 1.0881121  -0.4186427  -1.3011699 ]
 [ 1.2646016  -0.309021   -1.8083391 ]
 [ 0.36748448  0.46698555 -0.6090597 ]]


3. **Create a matrix C with dimensions 2x2, with values drawn from a normal distribution with mean 3 and stddev 0.5**

In [49]:
C = tf.random.normal(shape=(3, 2), mean=3.0, stddev=0.5)
print("Matrix C -")
print(C.numpy())

Matrix C -
[[2.5185537 3.117364 ]
 [3.6345057 3.5474246]
 [2.5503206 2.4992032]]


4. **Perform matrix addition between matrix A and matrix B, and store the result in matrix D**

In [51]:
D = tf.add(A, B)
print("Matrix D (A + B) -")
print(D.numpy())

Matrix D (A + B) -
[[ 1.6091425  -0.3815866  -0.13467681]
 [ 1.201957    1.7254415  -0.48528147]
 [ 1.6096356  -0.17084196 -1.1109889 ]]


5. **Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E**

In [53]:
# Adjusting dimensions so that C has the same number of columns as D has rows
D_adjusted = tf.random.normal(shape=(2, 3))  # Adjust D to have compatible dimensions with C
E = tf.matmul(C, D_adjusted)
print("Matrix E (C * D_adjusted) -")
print(E.numpy())

Matrix E (C * D_adjusted) -
[[-0.03733742  1.1686611   6.0744905 ]
 [ 0.26682985  1.4754949   7.7974567 ]
 [ 0.18386638  1.0375652   5.4816194 ]]


#### **Task 2: Performing Additional Matrix Operations**

1. **Create a matrix F with dimensions 3x3, initialized with random values using TensorFlow's random_uniform function.**

In [55]:
F = tf.random.uniform(shape=(3, 3), minval=0, maxval=1)
print("Matrix F -\n", F.numpy())

Matrix F -
 [[0.5993813  0.96921194 0.7094376 ]
 [0.0105319  0.7251221  0.27534592]
 [0.23653984 0.98289526 0.8611506 ]]


2. **Calculate the transpose of matrix F and store the result in matrix G.**

In [56]:
G = tf.transpose(F)
print("Matrix G (Transpose of F) -\n", G.numpy())

Matrix G (Transpose of F) -
 [[0.5993813  0.0105319  0.23653984]
 [0.96921194 0.7251221  0.98289526]
 [0.7094376  0.27534592 0.8611506 ]]


3. **Calculate the element-wise exponential of matrix F and store the result in matrix H.**

In [57]:
H = tf.exp(F)
print("Matrix H (Element-wise Exponential of F) -\n", H.numpy())

Matrix H (Element-wise Exponential of F) -
 [[1.8209919 2.6358664 2.0328476]
 [1.0105876 2.0649831 1.3169862]
 [1.266858  2.6721816 2.3658814]]


4. **Create a matrix I by concatenating matrix F and matrix G horizontally.**

In [58]:
I = tf.concat([F, G], axis=1)
print("Matrix I (F concatenated with G horizontally) -\n", I.numpy())

Matrix I (F concatenated with G horizontally) -
 [[0.5993813  0.96921194 0.7094376  0.5993813  0.0105319  0.23653984]
 [0.0105319  0.7251221  0.27534592 0.96921194 0.7251221  0.98289526]
 [0.23653984 0.98289526 0.8611506  0.7094376  0.27534592 0.8611506 ]]


5. **Create a matrix J by concatenating matrix F and matrix H vertically.**

In [59]:
J = tf.concat([F, H], axis=0)
print("Matrix J (F concatenated with H vertically) -\n", J.numpy())

Matrix J (F concatenated with H vertically) -
 [[0.5993813  0.96921194 0.7094376 ]
 [0.0105319  0.7251221  0.27534592]
 [0.23653984 0.98289526 0.8611506 ]
 [1.8209919  2.6358664  2.0328476 ]
 [1.0105876  2.0649831  1.3169862 ]
 [1.266858   2.6721816  2.3658814 ]]
